services:
  nginx_reverse_proxy:
    image: nginx:1.27
    container_name: proxy_nginx
    ports: 
      - "80:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./landing:/usr/share/nginx/html:ro
    networks:
      - is3_red
    restart: always

networks:
  is3_red:
    name: is3_red
    external: true
